blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://discord.gg/tSqtvHUJzE
    about: You can join the discussions on Discord.
  - name: Login does not work
    url: https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md
    about: Before opening a new issue, please make sure to read README.md
